### ISSUE TITLE
"ValueError: axes don't match array" in sample_segmentation_pairs_d.py

### ISSUE THREAD

**Issue by chibatoshikaze** [BBillot/SynthSeg#45]
Thank you for sharing synthseg. 

To train the denoiser in synthseg+,  I'm working on sample_segmentation_pairs_d.py, however, it returns "ValueError: axes don't match array". Here is the way the error is reproduced. 

Environment: requirements_python3.6.txt

1. Prepare image/lanel dataset by running scripts/tutorials/1-generation_visualisation.py
```
cd Synthseg/scripts/tutorials/
python 1-generation_visualisation.py 
```

2. Reproduce error by runinng following code. 
```
from SynthSeg.sample_segmentation_pairs_d import sample_segmentation_pairs

image_dir = './outputs_tutorial_1/image/image.nii.gz'
labels_dir = './outputs_tutorial_1/labels/labels.nii.gz'
results_dir = './outputs_tutorial_1/sample_seg_pair'
n_examples = 1
path_model = "../../models/synthseg_1.0.h5"
segmentation_labels = "../../data/labels_classes_priors/generation_labels.npy"

if __name__ == "__main__":
    sample_segmentation_pairs(
        image_dir=image_dir,
        labels_dir=labels_dir,
        results_dir=results_dir,
        n_examples=n_examples,
        path_model=path_model,
        segmentation_labels=segmentation_labels,
        n_neutral_labels=18, # n_neutral_labels=None,
        batchsize=1,
        flipping=True,
        scaling_bounds=.15,
        rotation_bounds=15,
        shearing_bounds=.012,
        translation_bounds=False,
        nonlin_std=3.,
        nonlin_scale=.04,
        min_res=1.,
        max_res_iso=4.,
        max_res_aniso=8.,
        noise_std_lr=3.,
        blur_range=1.03,
        bias_field_std=.5,
        bias_scale=.025,
        noise_std=10,
        gamma_std=.5)
```

3. This eventually return the error.
```
2023-01-28 11:42:52.894375: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-01-28 11:42:52.944030: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fee3e57bb80 executing computations on platform Host. Devices:
2023-01-28 11:42:52.944090: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Using TensorFlow backend.
Traceback (most recent call last):
  File "7-test-degradation_error.py", line 37, in <module>
    gamma_std=.5)
  File "/Users/chiba/Github/Riken-SynthSeg/SynthSeg/sample_segmentation_pairs_d_error.py", line 205, in sample_segmentation_pairs
    generation_model.load_weights(path_model, by_name=True)
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/keras/engine/network.py", line 1227, in load_weights
    reshape=reshape)
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 1294, in load_weights_from_hdf5_group_by_name
    reshape=reshape)
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/keras/engine/saving.py", line 980, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/chiba/anaconda3/envs/synthseg_env3.6/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by BBillot** [comment]
Hi,

so if you want to run sample_segmentation_pairs with `path_model = "../../models/synthseg_1.0.h5"`, then you would need the corresponding segmentation label list, which is located under SynthSeg/data/labels_classes_priors/synthseg_segmentation_labels.npy.

But I strongly suggest that you use real images as inputs to sample_segmentation_pairs, because SynthSeg will be very good on synthetic data, so the sampled segmentations will be pretty good. This is bad because those segmentations will utlimately be used to train D, and you need D to be exposed to bad segmentations, such that it knows how to deal with them at test time. 

More generally, note that I wrote tutorial 7, just to explain the mechanism of training SynthSeg+, so it's kind of a "sand-box" for users to experiment ;)

Hope this helps
Benjamin

**Comment by chibatoshikaze** [comment]
Thanks! 

When I fixed the code as mentioned and ran, I encountered following errors...
Please note that I tried two environments; with and without GPU machine. 
This eventually returns the different errors. 
(Could be my typo between machines, of course I double checked)

As below, do you think the code can load the corresponding segmentation labels with GPU, 
and the issue is Out of memory?

* Environment 1: 
macOS Monterey
Intel CPU (without GPU)
NOTE: Same machine in previous comments.

Error:  ValueError: axes don't match array
```
2023-03-05 11:50:15.595083: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-03-05 11:50:15.614121: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f78314d21e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-03-05 11:50:15.614158: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Using TensorFlow backend.
Traceback (most recent call last):
  File "7-test-degradation.py", line 28, in <module>
    sample_segmentation_pairs(
  File "/Users/chiba/Github/SynthSeg/SynthSeg/sample_segmentation_pairs_d_dev.py", line 205, in sample_segmentation_pairs
    generation_model.load_weights(path_model, by_name=True)
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/keras/engine/network.py", line 1225, in load_weights
    saving.load_weights_from_hdf5_group_by_name(
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/keras/engine/saving.py", line 1289, in load_weights_from_hdf5_group_by_name
    weight_values = preprocess_weights_for_loading(
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/keras/engine/saving.py", line 980, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 5, in transpose
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/chiba/anaconda3/envs/synthseg_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

* Environment 2: 
AWS g4dn.xlarge
GPU: Tesla T4

Error:  Out of memory 
```
2023-03-05 02:12:07.126992: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2023-03-05 02:12:07.184541: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.185136: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2023-03-05 02:12:07.185427: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2023-03-05 02:12:07.187318: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2023-03-05 02:12:07.188457: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2023-03-05 02:12:07.188786: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2023-03-05 02:12:07.190725: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2023-03-05 02:12:07.191829: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2023-03-05 02:12:07.195805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-03-05 02:12:07.195947: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.196562: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.197081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2023-03-05 02:12:07.197342: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2023-03-05 02:12:07.222530: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2499995000 Hz
2023-03-05 02:12:07.222841: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f9124000b60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-03-05 02:12:07.222868: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-03-05 02:12:07.325551: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.326210: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x3ef01c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-03-05 02:12:07.326241: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2023-03-05 02:12:07.326510: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.327086: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:00:1e.0 name: Tesla T4 computeCapability: 7.5
coreClock: 1.59GHz coreCount: 40 deviceMemorySize: 14.75GiB deviceMemoryBandwidth: 298.08GiB/s
2023-03-05 02:12:07.327168: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2023-03-05 02:12:07.327190: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2023-03-05 02:12:07.327223: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2023-03-05 02:12:07.327243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2023-03-05 02:12:07.327262: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2023-03-05 02:12:07.327280: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2023-03-05 02:12:07.327300: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-03-05 02:12:07.327383: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.327974: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.328513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
2023-03-05 02:12:07.328589: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2023-03-05 02:12:07.329305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-03-05 02:12:07.329328: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1108]      0 
2023-03-05 02:12:07.329338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] 0:   N 
2023-03-05 02:12:07.329477: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.330102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:981] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-05 02:12:07.330701: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1247] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14109 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:1e.0, compute capability: 7.5)
2023-03-05 02:12:22.282408: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2023-03-05 02:12:24.203807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2023-03-05 02:12:41.775504: W tensorflow/core/common_runtime/bfc_allocator.cc:245] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.52GiB with freed_by_count=0. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2023-03-05 02:12:41.775580: W tensorflow/core/kernels/gpu_utils.cc:49] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.
2023-03-05 02:12:48.380029: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 3623878656 exceeds 10% of free system memory.
2023-03-05 02:13:00.496689: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 3623878656 exceeds 10% of free system memory.
```
-> Eventually process kept running more than 10hours that I finally terminated. There were no output...

**Comment by chibatoshikaze** [comment]
Thank you for comment!

Here is the code I ran. 
Both environments installed the python3.8. 
It could be relevance to other mentions as #49.

I will try the followings; 
1. Cropping inout file

```python
from SynthSeg.sample_segmentation_pairs_d import sample_segmentation_pairs

image_dir = './outputs_tutorial_1/image.nii.gz'
labels_dir = './outputs_tutorial_1/labels.nii.gz'
results_dir = './outputs_tutorial_1/sample_seg_pair'
n_examples = 1
path_model = "../../models/synthseg_1.0.h5"
# segmentation_labels = "../../data/labels_classes_priors/generation_labels.npy"
segmentation_labels = "../../data/labels_classes_priors/synthseg_segmentation_labels.npy"

if __name__ == "__main__":
    sample_segmentation_pairs(
        image_dir=image_dir,
        labels_dir=labels_dir,
        results_dir=results_dir,
        n_examples=n_examples,
        path_model=path_model,
        segmentation_labels=segmentation_labels,
        n_neutral_labels=18, 
        batchsize=1,
        flipping=True,
        scaling_bounds=.15,
        rotation_bounds=15,
        shearing_bounds=.012,
        translation_bounds=False,
        nonlin_std=3.,
        nonlin_scale=.04,
        min_res=1.,
        max_res_iso=4.,
        max_res_aniso=8.,
        noise_std_lr=3.,
        blur_range=1.03,
        bias_field_std=.5,
        bias_scale=.025,
        noise_std=10,
        gamma_std=.5)
```

**Comment by BBillot** [comment]
the issue should be fixed now :)

two remarks though:

1. if you're using synthseg_1.0.h5, I would strongly recommend you tune down the augmentation, because it is less robust than synthseg 2.0. Another solution si to use synthseg 2.0:
`path_model = "../../models/synthseg_2.0.h5"`
`segmentation_labels = "../../data/labels_classes_priors/synthseg_segmentation_labels_2.0.npy"`
`n_neutral_labels = 19`

2. note that this script will give you segmentations with the label values of synthseg (ie.e for around 30 structures). However, these are probably note the labels that you want, since the training data for D should match the label values given by S1, which are typically way fewer (ie around 5).

**Comment by chibatoshikaze** [comment]
Thanks! 

1. I tried your comment as following code on my macOS (CPU), 
and it resulted in the same error; Error: ValueError: axes don't match array.
This happened in both of python 3.6 and 3.8. 

2. It makes sense. So when I run `sample_segmentation_pairs` for the degradation of S1 images, should I set the value `n_neutral_labels = 5`, `segmentation_labels = np.array([0, 1, 2, 3, 4])`, and `labels_dir = [label images predicted by S1]`?

Code;
```python
from SynthSeg.sample_segmentation_pairs_d import sample_segmentation_pairs

image_dir = './outputs_tutorial_1/image.nii.gz'
labels_dir = './outputs_tutorial_1/labels.nii.gz'
results_dir = './outputs_tutorial_1/sample_seg_pair'
n_examples = 1

# path_model = "../../models/synthseg_1.0.h5"
path_model = "../../models/synthseg_2.0.h5"

# segmentation_labels = "../../data/labels_classes_priors/synthseg_segmentation_labels.npy"
segmentation_labels = "../../data/labels_classes_priors/synthseg_segmentation_labels_2.0.npy"

n_neutral_labels = 19  #18

if __name__ == "__main__":
    sample_segmentation_pairs(
        image_dir=image_dir,
        labels_dir=labels_dir,
        results_dir=results_dir,
        n_examples=n_examples,
        path_model=path_model,
        segmentation_labels=segmentation_labels,
        n_neutral_labels=n_neutral_labels, 
        batchsize=1,
        flipping=True,
        scaling_bounds=.15,
        rotation_bounds=15,
        shearing_bounds=.012,
        translation_bounds=False,
        nonlin_std=3.,
        nonlin_scale=.04,
        min_res=1.,
        max_res_iso=4.,
        max_res_aniso=8.,
        noise_std_lr=3.,
        blur_range=1.03,
        bias_field_std=.5,
        bias_scale=.025,
        noise_std=10,
        gamma_std=.5)
```

Error;
```
Using TensorFlow backend.
2023-03-10 23:36:07.328249: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2023-03-10 23:36:07.386534: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa1a2e552d0 executing computations on platform Host. Devices:
2023-03-10 23:36:07.386562: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "7-test-degradation.py", line 59, in <module>
    gamma_std=.5)
  File "/Users/chiba/Github/SynthSeg/SynthSeg/sample_segmentation_pairs_d.py", line 205, in sample_segmentation_pairs
    generation_model.load_weights(path_model, by_name=True)
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/keras/engine/network.py", line 1227, in load_weights
    reshape=reshape)
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/keras/engine/saving.py", line 1294, in load_weights_from_hdf5_group_by_name
    reshape=reshape)
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/keras/engine/saving.py", line 980, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "<__array_function__ internals>", line 6, in transpose
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 651, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/Users/chiba/anaconda3/envs/synthseg36/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by chibatoshikaze** [comment]
It worked! Thank you very much! 

Sorry, I missed the commits. 
It worked with my own trained S1 network and real images either by pulling the current commit 
or by setting `n_labels = np.size(np.unique(segmentation_labels)` in the previous commit. 

Yes, I understand why the real images should be used. 

I will try to prepare an enough amount of sample segmentation pairs and to train the denoiser. 

Thank you!

**Comment by BBillot** [comment]
Sorry, but you also need to implement the other change of the commit https://github.com/BBillot/SynthSeg/commit/7f239508d77f17f23fa05a0d5fe1972c931890a6

In other words, please also delete lines 203->206 from SynthSeg/sample_segmentation_pairs_d.py:

```
        nn = np.sum(np.squeeze(outputs[1]).argmax(-1) > 0)
        if (nn > 500000) | (nn < 10000):
            continue
```

**Comment by chibatoshikaze** [comment]
Thank you. Apologies for the late reply. I was on vacation. 

By pulling the latest version, I generated the sample segmentation pairs for 1,000 pairs and started the training of denoiser. Thank you very much!

This is a minor question: Should I use all sample segmentation pairs generated by `sample_segmentation_pairs.py` or pick them up with the appropriate quality?

Because there are a variety of noisy labels in the labels_seg folder. In extreme cases, the entire image is filled with noise.

**Comment by chibatoshikaze** [comment]
Thank you! I understand why the denoiser needs to learn the good and bad segmentations. 
That's helpful, I will try managing the dataset imbalance.

Honestly, the prediction accuracy seems not good (denoising looks nice, but the segmentation doesn't) for my own dataset 
yet the train step reaches only 16 epoch. This might be caused by the imbalance of sample segmentation pairs as mentioned (now the ratio is approximately 2:8 for good and bad segmentations).

**Comment by chibatoshikaze** [comment]
May I ask once again about the denoiser? 

Do you think the following images are correct to use for training of denoiser? Input & output images were generated by ‘sample_seg_pairs.py’, and the predicted image was done by ‘predict_denoiser.py’. As mentioned, there are roughly two types of image pairs, NOISEY and LESS NOISY. The denoiser was trained by a dataset consisting of 10 pairs of each NOISEY and LESS NOISY, for a total of 20 pairs during 10 epochs.

* NOISY
![NOISEY](https://user-images.githubusercontent.com/38420437/234469216-8e674d47-ae1f-4da8-b2ed-9997445bcd2b.jpg)

* LESS NOISY
![LESS-NOISY](https://user-images.githubusercontent.com/38420437/234469208-4803bb4f-8078-4951-86fd-4fa5de1c300b.jpg)
